"""Output manager for saving charts and reports."""
import os
import json
from datetime import datetime
from typing import Dict, Any, Optional
import logging

logger = logging.getLogger(__name__)


class OutputManager:
    """Manages saving charts and markdown reports."""
    
    def __init__(self, output_dir: str = "outputs"):
        """
        Initialize the output manager.
        
        Args:
            output_dir: Directory to save outputs
        """
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)
        logger.info(f"[OUTPUT_MANAGER] Output directory: {output_dir}")
    
    def generate_filename(self, prefix: str, extension: str) -> str:
        """
        Generate a unique filename with timestamp.
        
        Args:
            prefix: Prefix for the filename
            extension: File extension (without dot)
        
        Returns:
            Filename string
        """
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        return f"{prefix}_{timestamp}.{extension}"
    
    def save_markdown_report(
        self,
        query: str,
        final_answer: str,
        chart_path: Optional[str] = None,
        chart_notes: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None
    ) -> str:
        """
        Save a markdown report with the query, answer, and chart.
        
        Args:
            query: User's original question
            final_answer: Final synthesized answer
            chart_path: Path to the chart file (if any)
            chart_notes: Notes about the chart (if any)
            metadata: Additional metadata to include
        
        Returns:
            Path to the saved markdown file
        """
        filename = self.generate_filename("report", "md")
        filepath = os.path.join(self.output_dir, filename)
        
        # Build markdown content
        content = f"""# Data Agent Report

## Query
**Date:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

**Question:**
```
{query}
```

---

## Analysis & Results

{final_answer}

"""
        
        # Add chart section if chart exists
        if chart_path:
            # Get relative path from outputs directory
            if os.path.exists(chart_path):
                rel_chart_path = os.path.relpath(chart_path, self.output_dir)
            else:
                rel_chart_path = chart_path
            
            content += f"""---

## Visualization

"""
            if chart_notes:
                content += f"**Chart Summary:** {chart_notes}\n\n"
            
            content += f"![Chart]({rel_chart_path})\n\n"
            content += f"**Chart File:** `{chart_path}`\n\n"
        
        # Add metadata section
        if metadata:
            content += """---

## Metadata

```json
"""
            content += json.dumps(metadata, indent=2)
            content += "\n```\n"
        
        # Add footer
        content += """
---

*Generated by Multi-Agent Data Analysis System*
"""
        
        # Save the file
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        
        logger.info(f"[OUTPUT_MANAGER] Saved markdown report: {filepath}")
        return filepath
    
    def extract_chart_info(self, content: str) -> tuple[Optional[str], Optional[str]]:
        """
        Extract chart path and notes from agent output.
        
        Args:
            content: Agent message content
        
        Returns:
            Tuple of (chart_path, chart_notes)
        """
        chart_path = None
        chart_notes = None
        
        if "CHART_PATH:" in content:
            try:
                # Extract chart path
                path_line = [line for line in content.split("\n") if "CHART_PATH:" in line][0]
                chart_path = path_line.split("CHART_PATH:")[1].strip()
                
                # Extract chart notes
                if "CHART_NOTES:" in content:
                    notes_line = [line for line in content.split("\n") if "CHART_NOTES:" in line][0]
                    chart_notes = notes_line.split("CHART_NOTES:")[1].strip()
                
                logger.info(f"[OUTPUT_MANAGER] Extracted chart info - Path: {chart_path}, Notes: {chart_notes}")
            except Exception as e:
                logger.error(f"[OUTPUT_MANAGER] Error extracting chart info: {e}")
        
        return chart_path, chart_notes
    
    def copy_chart_to_outputs(self, chart_path: str) -> Optional[str]:
        """
        Copy chart file to outputs directory.
        
        Args:
            chart_path: Original chart path
        
        Returns:
            New path in outputs directory, or None if failed
        """
        if not chart_path or not os.path.exists(chart_path):
            logger.warning(f"[OUTPUT_MANAGER] Chart file not found: {chart_path}")
            return None
        
        try:
            import shutil
            filename = os.path.basename(chart_path)
            new_path = os.path.join(self.output_dir, filename)
            
            # If file already in outputs, just return the path
            if os.path.abspath(chart_path) == os.path.abspath(new_path):
                return new_path
            
            shutil.copy2(chart_path, new_path)
            logger.info(f"[OUTPUT_MANAGER] Copied chart to: {new_path}")
            return new_path
        except Exception as e:
            logger.error(f"[OUTPUT_MANAGER] Error copying chart: {e}")
            return chart_path
